### PR TITLE
Merge attempt with official-stockfish/master and noobpwnftw/trainer

### PR DESCRIPTION
**Pull request by Sopel97**
This is an attempt to merge with official-stockfish/master and noobpwnftw/trainer. There are still important merge-related issues to resolve here.

1. Code that includes the net into the binary is excluded; do we want to include it?
2. Learn got simplified in noobpwnftw/trainer, many options like got removed. Do we want to bring them back? If so then how? Bringing back lambda is not trivial. (eta is under new name 'lr', do we revert this? I think lr is more descriptive.)
3. This includes the rotate180 -> rank_flip change. Do we want to revert this? (Personally I would say no, let's more forward)
4. Do we make halfkp+cr+ep the default now that it's working? (I would say yes)
5. Do we want to bring back `mirror` when loading data? I would say it's almost pointless with correct castling rights and flip.
6. I excluded noob's change to add the opening book. Should we include it with configurable path?

Then there are further, less critical things.
1. Castling rights features and ep features are not incremental. AppendChangedIndices needs to be reimplemented (castling is reversible btw.)

### CODE REVIEW

**Comment by nodchip** [comment]
Is it possible to train nets with the HEAD of nodchip/master and this pull request, and compare the Elo?  If the Elo of this pull request is higher, I would like to merge it.

> Code that includes the net into the binary is excluded; do we want to include it?

I think that we don't need to include the net into the binary.  Because it is not necessary for training data generation and trainer.

> Learn got simplified in noobpwnftw/trainer, many options like got removed. Do we want to bring them back? If so then how?

I think that we don't have to bring them back if the net trained with this pull request is stronger than the one trained with nodchip/master.

> Bringing back lambda is not trivial. (eta is under new name 'lr', do we revert this? I think lr is more descriptive.)

I also think that we don't have to bring back lambda if the net trained with this pull request is stronger.

> This includes the rotate180 -> rank_flip change. Do we want to revert this? (Personally I would say no, let's more forward)

I think that we don't have to revert it if the net trained with this pull request is stronger.  But we should change the version number of the nets so that users don't load wrong nets.

> Do we make halfkp+cr+ep the default now that it's working? (I would say yes)

We can think that we can make it default if the net is stronger.

> Do we want to bring back mirror when loading data? I would say it's almost pointless with correct castling rights and flip.

I think that we don't have to bring back mirror if the net trained with this pull request is stronger.

> I excluded noob's change to add the opening book. Should we include it with configurable path?

I think that it is better.  But we could do it in another pull request.

> Castling rights features and ep features are not incremental. AppendChangedIndices needs to be reimplemented (castling is reversible btw.)

I think that it is not a priority.  We could do it in another pull request.

**Comment by nodchip** [comment]
By the way, I don't see the Elo measurement results of noobpwnftw's nets.  Is there the Elo measurement results of his latest net?

**Comment by Sopel97** [comment]
https://tests.stockfishchess.org/tests/view/5f63224b912c15f19854b8a9 was the last test he made between a net trained by old trainer and his trainer. The code changed slightly since then. We should do a new test with this exact branch once CI passes. Since I don't have much resources the highest I can reasonably go is 10 million sfens per net, is this enough? You did a lot of testing like that so you have more experience. Also should the test be against the latest nodchip/master or the commit where the results were the best up to this point?

**Comment by nodchip** [comment]
10 million sfens per net should be enough for testing.  It would be best if we compare this pull request, 07-19 and nodchip/master with EnableTranspositionTable=false.

**Comment by Sopel97** [comment]
I have no idea why CI is failing at 147 of instrumented_learn. I cannot replicate it.

**Comment by noobpwnftw** [comment]
@Sopel97 Maybe you should change commands like "eta" -> "lr".

Yes, a very brief training can be used to measure performance.

**Comment by Sopel97** [comment]
@noobpwnftw I did.

**Comment by Sopel97** [comment]
I've scheduled 2 tests:
https://tests.stockfishchess.org/tests/view/5f6dca4bc2f42410187ab660 https://tests.stockfishchess.org/tests/view/5f6dca15c2f42410187ab65e

**Comment by vondele** [comment]
> I have no idea why CI is failing at 147 of instrumented_learn. I cannot replicate it.

reproduces here with the following error under valgrind:
```
$ ../tests/instrumented_learn.sh --valgrind
valgrind testing started
 expect gensfen01.exp 1>/dev/null
instrumented testing failed on line 147
$ expect gensfen01.exp
[...]
==12687== Conditional jump or move depends on uninitialised value(s)
==12687==    at 0x13FEEA: Tablebases::rank_root_moves(Position&, std::vector<Search::RootMove, std::allocator<Search::RootMove> >&) (search.cpp:1930)
==12687==    by 0x189780: Learner::MultiThinkGenSfen::get_current_game_result(Position&, std::vector<int, std::allocator<int> > const&) const (gensfen.cpp:477)
==12687==    by 0x189C3C: Learner::MultiThinkGenSfen::thread_worker(unsigned long) (gensfen.cpp:850)
==12687==    by 0x1AED14: MultiThink::go_think()::{lambda()#1}::operator()() const (multi_think.cpp:40)
==12687==    by 0x1AED3C: void std::__invoke_impl<void, MultiThink::go_think()::{lambda()#1}>(std::__invoke_other, MultiThink::go_think()::{lambda()#1}&&) (invoke.h:60)
==12687==    by 0x1AED52: std::__invoke_result<MultiThink::go_think()::{lambda()#1}>::type std::__invoke<MultiThink::go_think()::{lambda()#1}>(std::__invoke_result&&, (MultiThink::go_think()::{lambda()#1}&&)...) (invoke.h:95)
==12687==    by 0x1AED70: void std::thread::_Invoker<std::tuple<MultiThink::go_think()::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (thread:244)
==12687==    by 0x1AED7E: std::thread::_Invoker<std::tuple<MultiThink::go_think()::{lambda()#1}> >::operator()() (thread:251)
==12687==    by 0x1AED94: std::thread::_State_impl<std::thread::_Invoker<std::tuple<MultiThink::go_think()::{lambda()#1}> > >::_M_run() (thread:195)
==12687==    by 0x496BCB3: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==12687==    by 0x487B608: start_thread (pthread_create.c:477)
==12687==    by 0x4D46292: clone (clone.S:95)

```

**Comment by Sopel97** [comment]
I stopped the tests as it's pretty clear this branch is better than both 07-19 and the current master.

**Comment by Sopel97** [comment]
Noob's test https://tests.stockfishchess.org/tests/view/5f6dc744c2f42410187ab658 suggests that adding ep features is not beneficial on top of cr features and only slows the engine down. They can be easly removed from this PR. Should we? Even though the tests are indirect they are in my opinion meaningful.

**Comment by Sopel97** [comment]
This PR resolves #151, #149, and potentially #164

**Comment by Sopel97** [comment]
Looks like #164 still not resolved. We could probably keep this CI as the failing run is at the end.

**Comment by vondele** [comment]
not fully resolved, but progress. gensfen seems to be fine now, the learning part is not yet (a few different things it seems).

**Comment by noobpwnftw** [comment]
The two data race caught by tsan is as not a problem:
1. `learn_think.calc_loss(0, -1);` impersonates as thread 0 for initial loss calculation, this is done before other threads start running.
2. `Eval::NNUE::FinalizeNet();` sends a signal to clear unobserved weights, this is done after all threads ended.

**Comment by vondele** [comment]
so, should be fixable, if only to be able to rely on CI in the future.

**Comment by Sopel97** [comment]
I think this is ready for merge. The CI issue can be fixed in a separate PR as it's narrow. The incremental update for cr and ep features could also be done in a later PR (noob already has a working version I think).

**Comment by vondele** [comment]
yes, I don't think this should stop a merge as it is not a regression. 

I would wait to add the failing test for now, but that's a matter of taste (having things green, means that we don't have to explicitly look at the ouput to check if anything else fails).

**Comment by Sopel97** [comment]
Good point, I reverted the last commit.

**Comment by nodchip** [comment]
Thank you for sending this pull request, and experimenting training.  I merged it.

**Pull request merged**
