### PR TITLE
Add gensfen_nonpv

### PR DESCRIPTION
**Pull request by Sopel97**
Currently for experimentation. This gensfen takes positions from Eval::evaluate and rescores them later.

### CODE REVIEW

**Comment by vondele** [comment]
one idea I had in this context was to only add fens to the list if their evaluation is 'close' to the [alpha,beta] window (say, < 100cp). The idea is that only for those the evaluation actually matters, and probably that would yield more fens that are quiet.

**Comment by Sopel97** [comment]
Trained on 100M positions each.
```
setoption name SkipLoadingEval value true
setoption name Threads value 3
setoption name Use NNUE value pure
learn targetdir data epochs 1000 batchsize 100000 use_draw_in_training 1 use_draw_in_validation 1 lr 1 lambda 1 eval_limit 9000 nn_batch_size 1000 newbob_decay 0.99 eval_save_interval 25000000 loss_output_interval 1000000 max_grad 0.3 smart_fen_skipping set_recommended_uci_options
ucinewgame
```

results:
```
25k nodes per move, halfkae5-d4-nonpv vs halfkae5-d4:
Score of tuna vs stockfish: 368 - 293 - 339  [0.537] 1000
Elo difference: 26.11 +/- 17.52
```
Logs also look better:
d4: https://pastebin.com/M2UE5Pcd
d4-nonpv: https://pastebin.com/V02zhern

One sad thing is that this data doesn't compress. But it looks sound for training on.

As a sidenote. Depth 4 data did better than depth 9 data from noob:
```
25k nodes per move, d4 vs d9-noob:
Score of tuna vs stockfish: 369 - 316 - 315  [0.526] 1000
Elo difference: 18.43 +/- 17.83
```

Also
```
25k nodes per move, halfkae5-d9-noob vs nodchip-master-2020-12-12 (note: pure vs pure):
Score of tuna vs stockfish: 64 - 205 - 110  [0.314] 379
Elo difference: -135.77 +/- 30.76
```
25k nodes per move, halfkae5-d4-nonpv vs nodchip-master-2020-12-12 (note: pure vs pure):
Score of tuna vs stockfish: 79 - 185 - 124  [0.363] 388
Elo difference: -97.39 +/- 29.12

**Comment by nodchip** [comment]
Is this PR WIP, or can I merge it?

**Comment by Sopel97** [comment]
It's functional and doesn't affect other things, can be merged

**Comment by nodchip** [comment]
Thank you.  I merged it.

**Pull request merged**
