### PR TITLE
Small reorganization of learn stuff

### PR DESCRIPTION
**Pull request by Sopel97**
This PR contains the following changes:
- `use_raw_nnue_eval` is replaced by an uci option `Use NNUE value pure`. `Use NNUE` is 3 state only when compiled with -DEVAL_LEARN
- Moved scattered declarations in namespace Learner to respective headers in learn directory
- Split learn.h across other files that match the places they are defined.
- Rename learner.cpp to learn.cpp
- Moved sfen_packer from extra to learn (not sure why it was in extra in the first place?)
- Moved conditional definitions of some functions back to their respective files. For example functions in Position that are only compiled with EVAL_LEARN are now defined in position.cpp instead of sfen_packer.cpp
- Add base directory to include directories for compilation.
- Remove non-standard ".." in include paths in files from learn directory. (I left files from nnue directory as is, because they are reflected in the current official-stockfish/master.

References #132

### CODE REVIEW

**Comment by vondele** [comment]
did we want to get rid of -DEVAL_LEARN or keep it? I'm not quite sure what the value of the define is.  If I understand correctly, the functionality with EVAL_LEARN defined is strictly a superset of what we have without EVAL_LEARN defined, and the performance impact should be minimal?

**Comment by Sopel97** [comment]
Yes, it should be a superset. Nodchip said that he wants to keep make build to produce the binary about the same as master. I can live with EVAL_LEARN to signify differences from official-stockfish/master for now.

**Comment by nodchip** [comment]
I want to use fishtest when I merge the stockfish official to this repository to avoid regression.  If we remove EVAL_LEARN, additional if statements are added to the player part, and it causes speed down.  As the result, the regression test will fail.

**Comment by nodchip** [comment]
Thank you for the pull request.  I merged it.

**Comment by vondele** [comment]
I agree with the fishtest testing being a good idea, probably the speed impact could be measured. If it is small, one could probably ignore it, or just test with slightly shifted bounds like {-2, -1}. The advantage would be that we test the same code on fishtest as we use in the learning, so that we can be more confident about the learning code.

**Comment by nodchip** [comment]
I agree with test with bounds {-2, -1}.  And I'm fine to remove EVAL_LEARN magro.

**Comment by vondele** [comment]
@Sopel97 is the removal the EVAL_LEARN something you could tackle, with a test on fishtest?

**Comment by Sopel97** [comment]
Sure, but not earlier than tomorrow.

**Pull request merged**
