### PR TITLE
Restore lambda and gradient function post-merge and minor fixes.

### PR DESCRIPTION
**Pull request by noobpwnftw**
This restores the original "lambda" option and default net architecture, while provide fully functional support to other net architectures for future experiments.
Improved README to accommodate changes to parameters, and minor code reformat to make future merges easier.

### CODE REVIEW

**Comment by nodchip** [comment]
Thank you for the pull request.  I merged it.

**Comment by Sopel97** [comment]
So this reverts to the old calc_grad, but I thought it was worse?

**Comment by nodchip** [comment]
@Sopel97 You are right.  I missed this line.  https://github.com/nodchip/Stockfish/pull/166/files#diff-1725b65c5f524226147c027b73e7376bL228

@noobpwnftw Which is better do you think?

**Comment by noobpwnftw** [comment]
@Sopel97 @nodchip 
It is worse in terms of efficiency, but there are still a lot of use cases when people need to train with lambda 0, linear grad is not compatible with that, as discussed, to achieve the better results with the old grad and lambda 1, one may need to resample training data in regard to score distribution, or simply train with more iterations(mathematics show that it should eventually arrive at the same outcome).

**Comment by nodchip** [comment]
@noobpwnftw Thank you for the explanation.  Reverting looks reasonable for me.

**Pull request merged**
