### PR TITLE
10% to 15% speedups(depending on platform)

### PR DESCRIPTION
**Pull request by mstembera**
Optimize and clean up SSSE3, AVX2, and AVX512 implementations of Propagate().
AVX512 10% faster
AVX2 13% faster
SSSE3 15% faster

This superseeds PR https://github.com/nodchip/Stockfish/pull/62
bench: 3909820

@nodchip I know you are not merging atm but I wanted to let people who compile their own binaries have access to this.
Thanks.

### CODE REVIEW

**Comment by nodchip** [comment]
Thank you for the pull request.
I confirmed the speed up, and that the search PV is not changed with bench command.
I will leave this pull request until the part of NNUE is integrated in the original Stockfish, and ask you to send a pull request to the original Stockfish.

**Comment by joergoster** [comment]
@mstembera Pretty awesome!

**Comment by spasski** [comment]
Where can i find this sse42 exe for my bulldozer cpu?
Thx for all

**Comment by sf-x** [comment]
@mstembera can you prove your optimization is in fact sound? The sum of `product0` and `product1` can saturate. Yes, it's rare. I instrumented `ReadParameters` and found that indeed only a few weights (18, in all three layers, in the `nn.bin` I tested) are less than -64 or larger than 63. If there is none, your optimization is sound. It is also possible to limit them to 64 and fix up the result later (18 multiplies, add and stores aren't all that expensive)...

**Comment by sf-x** [comment]
OK, the optimization is also sound if *pairs* of coefficients which participate in `product0+product1` have sums between -128 and 128 inclusive. But then correctness can depend on SIMD width... Fun, isn't it?

**Comment by sf-x** [comment]
The condition in the revious comment is badly written, The weakest possible condition so far is: each int16 in `product0+product1` is `w_{j,i} v_i + w_{j,i+1} v_{i+1} +w_{j,i+s} v_{i+s} w_{j,i+s+1} v_{i+s+1}`, where `s` is he SIMD width. 
If `-257 <= w_{j,i} + w_{j,i+1} + w_{j,i+s} + w_{j,i+s+1}<=257` for relevant `i` then this optimization is sound.
I'm lazy and decided to only sum up adjacent weights, that is, check that `-128 <= w_{j,2i} + w_{j,2i+1} <=128` for all `i`,`j` where weights exist (rather than the above) to see how much of a problem that can be. (look at output mentioning `pairs` only.)

```
setoption name EvalFile value sergio-v\20200720-1017.bin
3 non-small weights
0 non-small pairs
12 non-small weights
3 non-small pairs
3 non-small weights
1 non-small pairs
info string NNUE sergio-v\20200720-1017.bin found & loaded
setoption name EvalFile value sergio-v\20200722-2141.bin
7 non-small weights
0 non-small pairs
11 non-small weights
3 non-small pairs
4 non-small weights
1 non-small pairs
info string NNUE sergio-v\20200722-2141.bin found & loaded
```
So for two `.bin` files mentioned above the optimization is guaranteed to work for the first (most expensive) layer. But what of others?

**Comment by dorzechowski** [comment]
@mstembera @nodchip I have pushed this commit to my branch [nnue-player-wip](https://github.com/dorzechowski/Stockfish/tree/nnue-player-wip) together with Makefile changes from PR #62. See also discussion in  [official-stockfish#2728](https://github.com/official-stockfish/Stockfish/issues/2728).

For me the speedup is consistent ~3% on ssse3, avx2 and bmi2 profile builds (i7-7700, Windows, gcc 9.3.0). I cannot test avx512. The bench is not changed and it plays well so I think it's good to have it in the branch. In case of problems it can be reverted later.

**Comment by mstembera** [comment]
@nodchip @joergoster  Thanks for testing.

@sf-x 
I thought about saturation as well.  Note the _mm256_maddubs_epi16() instruction already used by both master and patch takes 8 bit inputs and produces 16 bit outputs.  
https://software.intel.com/sites/landingpage/IntrinsicsGuide
It can also saturate as can the new _mm256_adds_epi16(product0, product1). However this would require all 4 consecutive 8 bit weights and corresponding inputs to be close to their theoretical maximums.  We don't seem to come even close to this.  I wrote an even faster version keeping the sum at 16 bits and never converting to 32 bits by _mm256_madd_epi16(product0, kOnes) until after everything was summed to convince myself this wasn't a problem.  The bench still didn't change.  When SFNNUE can run on fishtest we can do some experiments on top of that.

@dorzechowski Ok Thanks.

**Comment by nodchip** [comment]
@dorzechowski Thank you so much!  I will keep this pull request as-is until nnue-player-wip is integrated in the Stockfish master branch, and merge this pull request after that.

**Comment by sf-x** [comment]
> @sf-x
> I thought about saturation as well. Note the _mm256_maddubs_epi16() instruction already used by both master and patch takes 8 bit inputs and produces 16 bit outputs.
> https://software.intel.com/sites/landingpage/IntrinsicsGuide
> It can also saturate
Not as used in NNUE. Previous layer output values - I'll denote them by`v_i` - is clamped to [0,127]. Thus `-16256< w_{j,i} v_i < 16129` and the sum w_{j,i} v_i + w_{j,i+1} v_{i+1} can never overflow 16 bits.
> as can the new _mm256_adds_epi16(product0, product1). However this would require all 4 consecutive 8 bit weights and corresponding inputs to be close to their theoretical maximums. We don't seem to come even close to this. I wrote an even faster version keeping the sum at 16 bits and never converting to 32 bits by _mm256_madd_epi16(product0, kOnes) until after everything was summed to convince myself this wasn't a problem. The bench still didn't change. 
You see, you're cheating. The most problematic layers, as I noted, are the two smaller ones, and `_mm256` means you do each value of them in one shot and the problematic code never triggers.
>When SFNNUE can run on fishtest we can do some experiments on top of that.
...how many non-AVX2 machines are there?

**Comment by mstembera** [comment]
@sf-x 
OK I didn't realize we were guaranteed no saturation before due to the clamping.  I have updated the patch.  Thanks!
The new speed gains on my machine are:
AVX512 10% faster
AVX2 10% faster
SSSE3 8% faster
Most of it is due to the manual loop unrolling.  Compilers do this sometimes but the number of iterations has to be known at compile time which isn't the case here.

As a note..  Clamping the inputs is effectively saturation.  It just happens sooner in the pipeline.
Also I think we could clamp to 128 instead of 127 and give ourselves that extra bit more range w/o any issues.  Do you agree?

@dorzechowski  @nodchip  It looks like this hasn't made it into the new official SF nnue branch so I plan on opening a PR there.

**Comment by mstembera** [comment]
Also it is too bad the _mm512_dpbusds_epi32() intrinsic isn't part of the base AVX512 but only available with VNNI.  I think it could bring a nice speed up but I don't have the hardware to test.

**Comment by mstembera** [comment]
This https://github.com/official-stockfish/Stockfish/pull/2844
is now open so closing here.  Thanks.

**Pull request closed without merging**
