### PR TITLE
Update misc.cpp

### PR DESCRIPTION
**Pull request by FireFather**
do not clutter console/GUI window
remove "Windows large pages not used."
-only show message when/if successful

### CODE REVIEW

**Comment by FireFather** [comment]
Hi Noda...
I think it makes sense to suppress this message, and not spam the user with it

**Comment by nodchip** [comment]
Thank you for the pull request.  I think that we don't have to suppress this message because the original Stockfish also shows it.  Could we suppress if the original Stockfish suppress it?

**Comment by joergoster** [comment]
I don't like this either, but we should keep it as in master.

How about changing the name?
`  ss << "Stockfish-NNUE " << Version << setfill('0');`
and
```
  ss << (Is64Bit ? " 64" : "")
     << (HasPext ? " BMI2" : (HasPopCnt ? " POPCNT" : ""))
     << (to_uci  ? "\nid author ": " by ")
     << "T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda";
```
@nodchip Would this be correct?

**Comment by FireFather** [comment]
stockfish 11 doesn't show it...
I'll check the newest dev version

**Comment by FireFather** [comment]
well ok, yes, it's there in Stockfish 11...
strange thing is, I've never seen it output before...
and I use SF11 frequently
stockifish-nuue however, displays multiple times during use

**Comment by nodchip** [comment]
@joergoster 

> @nodchip Would this be correct?

> ss << "Stockfish-NNUE " << Version << setfill('0');

Sounds good.  But I would prefer "Stockfish+NNUE".

>     << "T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda";

Could you please also add the following developers?
- Y. Nasu (The original inventor of NNUE.)
- M. Isozaki (The training data generation and training logic.)

**Comment by FireFather** [comment]
const string Version = "11";
ss << "Stockfish-NNUE " << Version << setfill('0');

as you guys know, currently Version is filled with compile date if Version = ""
this is used in UCI 'id name'

is there something else preferable?  maybe something like gen, learn, and run?
Stockfish+NNUE learn 080720 64 BMI2

**Comment by FireFather** [comment]
this slight modification combines Version and date (Stockfish+NNUE learn 080720 64 BMI2)

const string Version = "learn";

const string engine_info(bool to_uci) {

  const string months("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec");
  string month, day, year;
  stringstream ss, date(__DATE__); // From compiler, format is "Sep 21 2008"

  ss << "Stockfish NNUE " << Version << " " << setfill('0');

  date >> month >> day >> year;
  ss << setw(2) << day << setw(2) << (1 + months.find(month) / 4) << year.substr(2);

  ss << (Is64Bit ? " 64" : "")
     << (HasPext ? " BMI2" : (HasPopCnt ? " POPCNT" : ""))
     << (to_uci  ? "\nid author ": " by ")
     << "T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda";
  return ss.str();
}

**Comment by joergoster** [comment]
How about setting Version to "dev"?

Here is what it would look like with the proposed changes:
```
id name Stockfish+NNUE dev 64 POPCNT
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda, Y. Nasu, M. Isozaki
```
However, I have no idea if some GUIs will eventually choke on the length of the second line now.

**Comment by FireFather** [comment]
dev works...I do like including date though, it supplies important info

**Comment by nodchip** [comment]
Could we postpone to add additional information which are not shown by the original Stockfish?

The changes will be:

```
  ss << "Stockfish+NNUE " << Version << setfill('0');

...

  ss << (Is64Bit ? " 64" : "")
     << (HasPext ? " BMI2" : (HasPopCnt ? " POPCNT" : ""))
     << (to_uci  ? "\nid author ": " by ")
     << "T. Romstad, M. Costalba, J. Kiiski, G. Linscott, H. Noda, Y. Nasu, M. Isozaki";
```

**Comment by joergoster** [comment]
That's fine. @FireFather Will you submit a PR with the changes?

**Comment by FireFather** [comment]
I'll leave this to you Joerg?

**Comment by FireFather** [comment]
lol ok

**Comment by joergoster** [comment]
Thank you, Norman!

**Comment by FireFather** [comment]
you can call me Norm

**Comment by nodchip** [comment]
Thank you for the pull request.  I merged it.

**Pull request merged**
