### PR TITLE
Rework loading the net after receiving 'ucinewgame'

### PR DESCRIPTION
**Pull request by joergoster**
instead of 'isready' command. This addresses #28 

**Main changes:**

- is_ready() renamed to init_nnue() and simplified, all calls to is_ready() replaced accordingly. There is no need to send empty lines which will at best be simply ignored. TT.resize() is automatically executed after a "setoption name Hash value xxx" anyway, and Search::clear() is done after "ucinewgame".
- The net will now be loaded after "ucinewgame", if necessary, and always after changing `EvalDir`.
- init_nnue() now included in both, the bench command and in the main UCI loop after receiving "ucinewgame" command. This will allow to do profile-builds with the NNUE net loaded.

### CODE REVIEW

**Comment by nodchip** [comment]
Thank you for the pull request.  I merged it.

**Comment by nodchip** [comment]
@joergoster 
I tried to train a net, and noticed that learn command crashes.  Could you take a look at it?

Steps to reproduce:
1. Compile a binary with the following command.
`make clean && make nnue-learn-use-blas ARCH=x86-64-bmi2 COMP=msys2 -j8`
2. Start training with the following uci command.
```
uci
setoption name SkipLoadingEval value true
setoption name Threads value 8
ucinewgame
learn targetdir training_data loop 100 batchsize 1000000 eta 1.0 lambda 0.5 eval_limit 32000 nn_batch_size 1000 newbob_decay 0.5 eval_save_interval 10000000 loss_output_interval 1000000 mirror_percentage 50 validation_set_file_name validation_data\generated_kifu.bin
```

Please replace "training_data" and "validation_data" to some folder path containing training data and validation data.

**Comment by joergoster** [comment]
@nodchip You're right!

The reason is the change in `void load_eval()` ... we must always do `NNUE::Initialze()`, of course! Otherwise a new net cannot be created by the learner.
I will submit a fix asap. Sorry for that.

**Comment by joergoster** [comment]
Just pushed a fix https://github.com/nodchip/Stockfish/pull/38. Learning works for me, again!

Could you please confirm? Thank you!

**Comment by nodchip** [comment]
I will check it.  Thank you.

**Pull request merged**
