### PR TITLE
Fix two cases of crash

### PR DESCRIPTION
**Pull request by noobpwnftw**
Fix https://github.com/nodchip/Stockfish/issues/107, and bench command on learn compiles without a net.

### CODE REVIEW

**Comment by Sopel97** [comment]
I think the full fix requires changing `use_raw_nnue_eval` default to false in learner.cpp.

**Comment by noobpwnftw** [comment]
Yes indeed, but I'm reluctant to changing any defaults.

**Comment by Sopel97** [comment]
The problem with this defaulting to true is that there's no way of changing that without running learn first. True would be fine as a default, but it would need to be an uci option. IMO considering how spread the use of `use_raw_nnue_eval` is it would be best to go cfish way - a 3 state Use NNUE.

**Comment by nodchip** [comment]
A 3 state Use NNUE sounds reasonable for me.  Maybe we could:
- change the `Use NNUE` option to combo,
- add three options, `true`, `false` and `force`,
- define the corresponding enum `USE_NNUE`,
- change useNNUE to `USE_NNUE useNNUE`, and 
- change Eval::evalute() to switch the logic according to useNNUE.

**Comment by noobpwnftw** [comment]
In my opinion, this option makes no sense.

**Comment by nodchip** [comment]
@noobpwnftw I want to discuss your commit, https://github.com/nodchip/Stockfish/commit/b4be26456f97118a49773f41a41d365bcf7cf60e.  But I think this issue is not the right place to discuss.  Could you please create another pull request?

**Comment by noobpwnftw** [comment]
I'll close this one because fixing the apparent crashes have no meaning if the underlying logic is not correct. We can discuss in discord.

**Pull request closed without merging**
