### PR TITLE
Revert to rotate // delete old k-p arch files

### PR DESCRIPTION
**Pull request by NightlyKing**

### CODE REVIEW

**Comment by Sopel97** [comment]
This was discussed to great length on discord among the devs, and the consensus is that we'll revert rotate as no one trained a better net with flip and flip prevents us from using the best nets in gensfen.

**Comment by NightlyKing** [comment]
I added the google document with coding priorities and vondeles gensfen dump to the readme as this is more of a maintenance PR anyway.

**Comment by NightlyKing** [comment]
I also changed halfka to rotate so that arch also compiles correctly. We have no actual data which approach is best for halfka (although flip should be superior) so I added that to the comment.

**Comment by nodchip** [comment]
@NightlyKing Thank you for the pull request.  Unfortunately, the CI test failed.  Could you please take a look at it?

**Comment by vondele** [comment]
../tests/instrumented.sh --valgrind-thread

```
==12896== Thread 2:

==12896== Conditional jump or move depends on uninitialised value(s)

==12896==    at 0x142C10: UCI::pv[abi:cxx11](Position const&, int, Value, Value) (search.cpp:1842)

==12896==    by 0x144A2E: MainThread::search() (search.cpp:270)

==12896==    by 0x14AEF5: Thread::idle_loop() (thread.cpp:143)

==12896==    by 0x14B6F0: void* start_routine<Thread, std::pair<Thread*, void (Thread::*)()> >(void*) (thread_win32_osx.h:40)

==12896==    by 0x4862608: start_thread (pthread_create.c:477)

==12896==    by 0x4D2D292: clone (clone.S:95)

==12896== 

==12896== Conditional jump or move depends on uninitialised value(s)

==12896==    at 0x142DA1: UCI::pv[abi:cxx11](Position const&, int, Value, Value) (search.cpp:1857)

==12896==    by 0x144A2E: MainThread::search() (search.cpp:270)

==12896==    by 0x14AEF5: Thread::idle_loop() (thread.cpp:143)

==12896==    by 0x14B6F0: void* start_routine<Thread, std::pair<Thread*, void (Thread::*)()> >(void*) (thread_win32_osx.h:40)

==12896==    by 0x4862608: start_thread (pthread_create.c:477)

==12896==    by 0x4D2D292: clone (clone.S:95)

==12896== 

==12896== Conditional jump or move depends on uninitialised value(s)

==12896==    at 0x142ED7: UCI::pv[abi:cxx11](Position const&, int, Value, Value) (search.cpp:1872)

==12896==    by 0x144A2E: MainThread::search() (search.cpp:270)

==12896==    by 0x14AEF5: Thread::idle_loop() (thread.cpp:143)

==12896==    by 0x14B6F0: void* start_routine<Thread, std::pair<Thread*, void (Thread::*)()> >(void*) (thread_win32_osx.h:40)

==12896==    by 0x4862608: start_thread (pthread_create.c:477)

==12896==    by 0x4D2D292: clone (clone.S:95)

==12896== 
```

**Comment by Sopel97** [comment]
rootInTB is not initialized when there is no root moves.
thread.cpp around line 250:
```
      if (!rootMoves.empty())
          Tablebases::rank_root_moves(pos, rootMoves);
```
We should at least initialize th->rootInTB to false in this function. Not sure why it's only popping up now...

**Comment by nodchip** [comment]
Thank you for the pull request.  I merged it.

**Pull request merged**
