### PR TITLE
Add initialization also to learning patch

### PR DESCRIPTION
**Pull request by vondele**
fixes https://github.com/nodchip/Stockfish/issues/160

### CODE REVIEW

**Comment by noobpwnftw** [comment]
After last TB change, once TB is hit(and dtz present), ProbeDepth is set to zero and subsequent search on the thread will no longer probe in search. All those variables needs to be moved under each thread.

**Comment by vondele** [comment]
can you make a PR for that?

**Comment by nodchip** [comment]
@vondele Thank you for the pull request.  I merged it.

@noobpwnftw Could you please make a pull request for it?

**Comment by nodchip** [comment]
The CI test of master is failed because tests.stockfishchess.org is down now.  I will restart the test after the server comes back.

**Pull request merged**
