### PR TITLE
Add AVX2 and AVX512 to engine info printed at startup

### PR DESCRIPTION
**Pull request by mstembera**
Helps to identify the type of binary.  More could be added but I don't know how fine grained you want to go with this.

### CODE REVIEW

**Comment by nodchip** [comment]
Thank you for the pull request.
I and some people from Stockfish community are working on integrating NNUE in the official branch of Stockfish.  I'm stopping modifying my repository to avoid interferes with those works.
I will ask you to send this pull request to the official branch once the part of the integration are done.

**Comment by mstembera** [comment]
That's great news!  Just let me know.  Is there somewhere  I can follow the developments?

**Comment by nodchip** [comment]
You can see the progress here.
https://github.com/official-stockfish/Stockfish/issues/2728

**Comment by dorzechowski** [comment]
@mstembera @nodchip I have pushed this commit to my branch [nnue-player-wip](https://github.com/dorzechowski/Stockfish/tree/nnue-player-wip) in case it will be used on fishtest. See also discussion in  [official-stockfish#2728](https://github.com/official-stockfish/Stockfish/issues/2728).

**Comment by nodchip** [comment]
@dorzechowski Thank you so much!  I will keep this pull request as-is until nnue-player-wip is integrated in the Stockfish master branch, and merge this pull request after that.

**Comment by mstembera** [comment]
Opened https://github.com/official-stockfish/Stockfish/pull/2845
so closing this.  Thanks.

**Pull request closed without merging**
