### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by noobpwnftw**
Real man.

### CODE REVIEW

**Comment by vondele** [comment]
Cool! thanks.

**Comment by nodchip** [comment]
@noobpwnftw Could you please rebase this PR?

**Comment by nodchip** [comment]
@noobpwnftw The GitHub page still shows "This branch cannot be rebased due to conflicts".  Could you please take a look at it?

**Comment by noobpwnftw** [comment]
Why do you need a rebase? I can merge current master here without problems.

**Comment by Sopel97** [comment]
I also see no conflicts here

**Comment by nodchip** [comment]
OK.  I merged this PR.  Thank you.

**Pull request merged**
