### PR TITLE
comments translated to English

### PR DESCRIPTION
**Pull request by FireFather**
most files reformatted from 2 to 4 (MSVC default) space indentation

### CODE REVIEW

**Comment by ianfab** [comment]
I would recommend to not change indentation in files that originate from official SF, since using a different indentation would complicate upstream merges. For files specific to the NNUE fork that of course is not relevant.

**Comment by FireFather** [comment]
Yes, agreed.  Had actually considered that.
When I have some time I'll prepare it again...

**Comment by joergoster** [comment]
@FireFather I would also suggest to split this into several PRs. As a whole, it is almost impossible to review.

**Comment by FireFather** [comment]
Hi Jörg 
yeah, that makes sense 

Is this something that nodchip even wants done? 

Let me know, because it's certainly not much fun... 

[ https://github.com/FireFather/sf-nnue | https://github.com/FireFather/sf-nnue ] 

Norm

**Comment by nodchip** [comment]
Translation is welcome because it helps many other developers to understand the source code.  I guess that it will help to improve the elo.
Fixing indentations is also good.  But I think that it does not improve the elo.  We could postpone to fix indentations.

@FireFather Could you please create another pull request to translate?  I'm sorry but I will close this pull request.

**Comment by FireFather** [comment]
Of course!
I've had them done for some time now...here https://github.com/FireFather/sf-nnue
Congrats on your great ideas and a fine project!

**Pull request closed without merging**
