### PR TITLE
Cleanup eval saving and lr scheduling.

### PR DESCRIPTION
**Pull request by Sopel97**

### CODE REVIEW

**Comment by nodchip** [comment]
@Sopel97 Could you please check the CI result, and fix the source code?

**Comment by Sopel97** [comment]
Okay, I didn't notice that this depends on some other commit. The PR needs to be deferred a bit.

**Comment by Sopel97** [comment]
Should be ready now.

**Comment by nodchip** [comment]
I confirmed some logic are extracted to bool LearnerThink::check_progress().  Thank you.

**Pull request merged**
