### PR TITLE
Cleanup 2020 10 14

### PR DESCRIPTION
**Pull request by Sopel97**
This PR performs many cosmetic changes, mostly on the previously untouched parts of the code. In particular:

- moved nnue evaluation related code from evaluate.h to nnue/evaluate_nnue.h
- change namespace of the public search routines from Learner to Search
- move sfen input/output stream code into a separate file
- adjust indentation to match the rest of the learner code.
- rename "hirate eval" to "startpos eval"
- increase spacing between training progress health output
- show a message to the user when there's no net loaded during learning
- more empty lines in the nnue code for increased readability
- aligned all preprocessor directives to the left
- removed ".." from include paths
- merged nested namespaces
- changed PascalCase function names to snake_case to match the rest of the codebase

### CODE REVIEW

**Comment by nodchip** [comment]
@Sopel97 This PR is too big to review.  Could you please split this PR into several PRs?

**Comment by Sopel97** [comment]
I can try...

**Comment by Sopel97** [comment]
Best I can do is a chain of PRs that have to be merged in order, and if there are change requests it may break all further ones. They are too dependent on each other because they move a lot of stuff

**Comment by nodchip** [comment]
Thank you.  I will check them.

**Comment by nodchip** [comment]
Unfortunately, there was a conflict between A and B.  I will resolve the conflict and merge one by one.

**Comment by Sopel97** [comment]
weird, there should be no conflicts

**Pull request closed without merging**
